language: python
python:
  - 2.6
  - 2.7
env:
  - REQUESTS_VERSION=">=1.0,<2.0"
  - REQUESTS_VERSION=">=2.0"
install:
  - pip install -e .
  - pip install -q requests$REQUESTS_VERSION
  - pip install -r requirements_test.txt
script:
  - py.test --cov colourlovers
after_success:
  - coveralls
