language: python
python:
  - 2.6
  - 2.7
env:
  - REQUESTS_VERSION=">=1.0,<1.1"
  - REQUESTS_VERSION=">=1.1,<1.2"
  - REQUESTS_VERSION=">=1.2"
install:
  - pip install -q requests$REQUESTS_VERSION
  - pip install -r requirements_test.txt
script:
  - ./runtests.sh --with-coverage --cover-package=colourlovers
after_success:
  - coveralls
